# Generated by Django 4.1.7 on 2023-03-28 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.TextField()),
                ('Email', models.EmailField(max_length=254)),
                ('review_text', models.TextField()),
                ('sentiment', models.CharField(max_length=10)),
            ],
        ),
    ]
